name: Lint from a PR

on: pull_request

env:
  DBT_PROFILE_TARGET:            test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq to parse json
      run: sudo apt-get install jq

    - name: event info
      run: |
        jq . $GITHUB_EVENT_PATH
    
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: fetch main branch for sqlfluff to compare
      run: git fetch origin main

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install sqlfluff
      run: |
        python -m pip install --upgrade pip
        pip install sqlfluff

    - name: Lint SQL check
      run: |
        git branch
        git log -5

    - name: Lint SQL
      run: |
        diff-quality --violations sqlfluff --compare-branch origin/main
