name: Lint from a PR

on: pull_request

env:
  DBT_PROFILE_TARGET:            test

jobs:
  test:
    runs-on: ubuntu-latest

    - name: Checkout Main
      uses: actions/checkout@v2
      with:
        path: main

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install sqlfluff
      run: |
        python -m pip install --upgrade pip
        pip install sqlfluff

    - name: Lint SQL
      run: |
        diff-quality --violations sqlfluff --compare-branch origin/main