name: Lint from a PR

on: pull_request

env:
  DBT_PROFILE_TARGET:            test

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR by removing the merge into main
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: event info
      run: |
        jq . $GITHUB_EVENT_PATH

    - name: fetch main branch for sqlfluff to compare
      run: |
        git fetch origin main:main  
        git branch

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install dbt
        pip install sqlfluff

    - name: Lint SQL
      run: |
        diff-quality --violations sqlfluff --compare-branch origin/main
