version: 2

exposures:
  - name: Orders (Prod)
    type: dashboard                        # required
    maturity: high                          # optional
    url: https://bi.tool/datasource/1       # optional
    description: >                          # optional
      Did someone say "exponential growth"?
    
    depends_on:                             # expected
      - ref('fct_orders')
      - ref('dim_customers')
      # - source('gsheets', 'goals')

    owner:
      name: Claire from Data                # optional
      email: data@jaffleshop.com            # required
  
  - name: Jaffle Shop - Orders by Customer
    type: dashboard                         # required
    maturity: high                          # optional
    url: https://bi.tool/dashboards/1       # optional
    description: >                          # optional
      Did someone say "exponential growth"?
    
    depends_on:                             # expected
      - ref('fct_orders')
      - ref('dim_customers')

    owner:
      name: Claire from Data                # optional
      email: data@jaffleshop.com            # required
  
  - name: Jaffle Shop - Orders by Week
    type: dashboard                         # required
    maturity: high                          # optional
    url: https://bi.tool/dashboards/1       # optional
    description: >                          # optional
      Did someone say "exponential growth"?
    
    depends_on:                             # expected
      - ref('fct_orders')
      - ref('dim_customers')

    owner:
      name: Claire from Data                # optional
      email: data@jaffleshop.com            # required

  